---
prometheus:
  thanosIngress:
    hosts:
      - prod.thanos.p4.greenpeace.org
    annotations:
      kubernetes.io/ingress.class: nginx
    tls:
      - secretName: thanos-tls
        hosts:
          - prod.thanos.p4.greenpeace.org
