---
kubeStateMetrics:
  enabled: true
kube-state-metrics:
  image:
    repository: quay.io/coreos/kube-state-metrics
    tag: v1.8.0
    pullPolicy: IfNotPresent
  collectors:
    # Not supported in 1.8 needed for K8 1.15
    volumeattachments: false
    validatingwebhookconfigurations: false
    mutatingwebhookconfigurations: false
    networkpolicies: false
alertmanager:
  resources:
    limits:
      cpu: 10m
      memory: 32Mi
    requests:
      cpu: 10m
      memory: 32Mi
nodeExporter:
  resources:
    limits:
      cpu: 200m
      memory: 50Mi
    requests:
      cpu: 100m
      memory: 30Mi
server:
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 512Mi
pushgateway:
  resources:
    limits:
      cpu: 10m
      memory: 32Mi
    requests:
      cpu: 10m
      memory: 32Mi
