---
prometheus:
  server:
    persistentVolume:
      enabled: true
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi

prometheusOperator:
  createCustomResource: false

grafana:
  persistence:
    enabled: true
  # storageClassName: default
  accessModes:
    - ReadWriteOnce
  size: 10Gi
