---
prometheus:
  server:
    persistentVolume:
      enabled: true
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi
grafana:
  persistence:
    enabled: true
  # storageClassName: default
  accessModes:
    - ReadWriteOnce
  size: 10Gi

kubeStateMetrics:
  enabled: true
kube-state-metrics:
  image:
    repository: quay.io/coreos/kube-state-metrics
    tag: v1.9.7
    pullPolicy: IfNotPresent
