---
prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: standard
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 30Gi
    retention: 10d

prometheusOperator:
  admissionWebhooks:
    enabled: false
    patch:
      enabled: false
  tlsProxy:
    enabled: false

grafana:
  persistence:
    enabled: true
  # storageClassName: default
  accessModes:
    - ReadWriteOnce
  size: 10Gi
