---
prometheus:
  service:
    additionalPorts:
      - name: thanos-grpc
        protocol: TCP
        port: 10901
  prometheusSpec:
    additionalAlertManagerConfigs:
      - scheme: https
        tls_config:
          ca_file: /certs/cacerts.pem
          cert_file: /certs/tls.crt
          key_file: /certs/tls.key
          server_name: "alertmanager-0.greenpeace.net"
        static_configs:
          - targets:
              - "alertmanager-0.greenpeace.net"
      - scheme: https
        tls_config:
          ca_file: /certs/cacerts.pem
          cert_file: /certs/tls.crt
          key_file: /certs/tls.key
          server_name: "alertmanager-1.greenpeace.net"
        static_configs:
          - targets:
              - "alertmanager-1.greenpeace.net"
      - scheme: https
        tls_config:
          ca_file: /certs/cacerts.pem
          cert_file: /certs/tls.crt
          key_file: /certs/tls.key
          server_name: "alertmanager-2.greenpeace.net"
        static_configs:
          - targets:
              - "alertmanager-2.greenpeace.net"
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: standard
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 30Gi
    volumes:
      - name: certs
        secret:
          secretName: thanos-tls
    volumeMounts:
      - name: certs
        mountPath: "/certs"
        readOnly: true
    retention: 10d
    thanos:
      version: v0.20.1
      objectStorageConfig:
        name: thanos-key
        key: objstore.yml
  thanosIngress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: GRPC
      nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
      nginx.ingress.kubernetes.io/grpc-backend: 'true'
      nginx.ingress.kubernetes.io/protocol: h2c
      nginx.ingress.kubernetes.io/proxy-read-timeout: '160'
      nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
      nginx.ingress.kubernetes.io/auth-tls-verify-depth: "2"
      nginx.ingress.kubernetes.io/auth-tls-secret: "kube-system/thanos-tls"
prometheusOperator:
  createCustomResource: false
  admissionWebhooks:
    enabled: false
    patch:
      enabled: false
  tlsProxy:
    enabled: false
grafana:
  persistence:
    enabled: true
  # storageClassName: default
  accessModes:
    - ReadWriteOnce
  size: 10Gi

alertmanager:
  enabled: false
