---
kubeStateMetrics:
  enabled: true
kube-state-metrics:
  image:
    repository: quay.io/coreos/kube-state-metrics
    tag: v1.8.0
    pullPolicy: IfNotPresent
  collectors:
    # Not supported in 1.8 needed for K8 1.15
    volumeattachments: false
    validatingwebhookconfigurations: false
    mutatingwebhookconfigurations: false
    networkpolicies: false
