---
grafana:
  ingress:
    enabled: true
    hosts:
      - grafana.p4.greenpeace.org
    path: /
    annotations:
      kubernetes.io/ingress.class: traefik
prometheus: 
  thanosIngress:
    hosts:
      - thanos.p4.greenpeace.org
    annotations:
      kubernetes.io/ingress.class: nginx
    tls:
      - secretName: thanos-tls
        hosts:
          - thanos.p4.greenpeace.org
