---
grafana:
  ingress:
    enabled: true
    hosts:
      - grafana.p4.greenpeace.org
    path: /
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/auth-signin: >-
        https://nginx-oauth.greenpeace.org/oauth2/p4/start?rd=https://$host$uri
      nginx.ingress.kubernetes.io/auth-url: >-
        https://nginx-oauth.greenpeace.org/oauth2/p4/auth
    tls:
      - secretName: grafana-tls
        hosts:
          - grafana.p4.greenpeace.org
prometheus:
  thanosIngress:
    hosts:
      - thanos.p4.greenpeace.org
    annotations:
      kubernetes.io/ingress.class: nginx
    tls:
      - secretName: thanos-tls
        hosts:
          - thanos.p4.greenpeace.org
